### ISSUE TITLE
srvany-ng blocks all network access

### ISSUE THREAD

**Issue by kibeb** [birkett/srvany-ng#4]
It seems to me srvany-ng blocks all network access for the process it launches.
(And running the service under an account different from Local System doesn't help.)

Everything works like it should immediately after changing just the registry value _ImagePath_ from _srvany-ng.exe_ to the old _srvany.exe_ and starting the service again.

I found out while trying to setup a perl networking app, but even running simple `cmd.exe /c c:\work\test.cmd` where _test.cmd_ contains:
`ping 127.0.0.1 > c:\work\test.txt`
creates just empty test.txt file (while with srvany.exe test.txt contains the correct ping output).

Thanks.

**Comment by birkett** [comment]
Unable to reproduce this - tested back when first raised on Windows 10, following the example provided.
Tested today on Windows 11 - still unable to reproduce.

My test service config:
![image](https://github.com/user-attachments/assets/be868747-f7a6-4823-9853-cb2425e55f6d)

And the result:
![image](https://github.com/user-attachments/assets/3311b1dc-fc44-4887-8887-1ff23483f032)


Please re-open if you have further steps to reproduce.
