### ISSUE TITLE
Readme typo in binPath arg

### ISSUE THREAD

**Issue by fiddyschmitt** [birkett/srvany-ng#5]
Hi Anthony,

In your readme, the `sc create` command has an unecessary space between `binPath` and its equal sign.

`sc create "MyServiceName" start= auto binPath = "C:\Path\To\srvany-ng.exe"`

Should be:

`sc create "MyServiceName" start= auto binPath= "C:\Path\To\srvany-ng.exe"`

Thank you,
Fidel

**Comment by SadPencil** [comment]
https://github.com/birkett/srvany-ng/pull/3

However the owner does not response to this PR

**Comment by SadPencil** [comment]
Hi Anthony @birkett, would you please merge PR #3 to fix this issue?
