### ISSUE TITLE
I propose to deprecate https://github.com/birkett/srvany-ng

### ISSUE THREAD

**Issue by vporton** [birkett/srvany-ng#6]
I propose to deprecate https://github.com/birkett/srvany-ng in regard of https://github.com/vporton/srvany-ng because installation/deinstallation of services should be done by the installer itself, not by custom commands.

Deprecation can be expressed as a noticeable link "better use that".

Note however, `FIXME` comments in the source of https://github.com/vporton/srvany-ng.

**Comment by birkett** [comment]
This directly contravenes the original purpose of srvany-ng - that was to be a drop in replacement for the w2k3 res kit binary.
While you are free to continue development on the fork, this original project will remain.
